drop table if exists pharmacies CASCADE;

create table pharmacies (
    id bigint generated by default as identity,
    address varchar(255),
    city varchar(255),
    name varchar(255) not null,
    token varchar(255),
    primary key (id)
);

alter table pharmacies add constraint pharmacies_unique_name unique (name);
